import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { Link, useParams } from 'react-router-dom';
import { adminUsers, allEvents, matches, players, scheduleEntries, teams } from '../../data/mockData';
import { Button, Input, SearchInput, Select } from '../../components/ui/FormControls';
import { EmptyState, PageContainer, SectionHeader, StatCard } from '../../components/ui/Primitives';

export function AdminLoginPage({ onLogin }: { onLogin: () => void }) {
  const { register, handleSubmit } = useForm<{ email: string; password: string }>();
  return <PageContainer title="Admin Login" subtitle="Mock auth only"><form className="card mx-auto max-w-md space-y-3 p-4" onSubmit={handleSubmit(() => onLogin())}><Input placeholder="Email" {...register('email')} /><Input type="password" placeholder="Password" {...register('password')} /><Button type="submit">Sign in</Button></form></PageContainer>;
}

export const AdminDashboardPage = () => <PageContainer title="Admin Dashboard"><div className="grid grid-cols-2 gap-3 md:grid-cols-6"><StatCard label="Teams" value={teams.length} /><StatCard label="Players" value={players.length} /><StatCard label="Matches" value={matches.length} /><StatCard label="Events" value={allEvents.length} /><StatCard label="Pending" value={matches.filter((m)=>m.status==='upcoming').length} /><StatCard label="Soon" value={scheduleEntries.length} /></div></PageContainer>;

export function AdminTeamsPage(){const [q,setQ]=useState(''); const list=teams.filter((t)=>t.name.toLowerCase().includes(q.toLowerCase())); return <PageContainer title="Admin Teams" action={<Button>Create team</Button>}><SearchInput placeholder="Search team" value={q} onChange={(e)=>setQ(e.target.value)} /><div className="mt-3 space-y-2">{list.map((t)=><div key={t.id} className="card flex items-center justify-between p-3"><span>{t.name}</span><div className="flex gap-2"><Button variant="secondary">Edit</Button><Link className="btn btn-secondary" to={`/teams/${t.id}`}>Open</Link></div></div>)}</div></PageContainer>}

export function AdminPlayersPage(){return <PageContainer title="Admin Players" action={<Button>Add player</Button>}><div className="card overflow-hidden"><table className="w-full text-sm"><thead className="bg-zinc-100"><tr><th className="p-2 text-left">Name</th><th>Team</th><th>Status</th><th></th></tr></thead><tbody>{players.map((p)=><tr key={p.id} className="border-t"><td className="p-2">{p.displayName}</td><td>{teams.find((t)=>t.id===p.teamId)?.shortName}</td><td>{p.status}</td><td><Button variant="secondary" className="my-1">Edit</Button></td></tr>)}</tbody></table></div></PageContainer>}

export function AdminMatchesPage(){const [status,setStatus]=useState('all'); return <PageContainer title="Admin Matches" action={<Button>Create match</Button>}><Select value={status} onChange={(e)=>setStatus(e.target.value)}><option value='all'>All statuses</option><option value='upcoming'>Upcoming</option><option value='live'>Live</option><option value='finished'>Finished</option></Select><div className="mt-3 space-y-2">{matches.filter((m)=>status==='all'||m.status===status).map((m)=><div key={m.id} className="card flex items-center justify-between p-3"><p>R{m.round}: {teams.find((t)=>t.id===m.homeTeamId)?.shortName} vs {teams.find((t)=>t.id===m.awayTeamId)?.shortName}</p><Link className="btn btn-primary" to={`/admin/matches/${m.id}/result`}>Result editor</Link></div>)}</div></PageContainer>}

export function AdminMatchResultEditorPage(){const {id=''}=useParams(); const match=matches.find((m)=>m.id===id); if(!match) return <PageContainer title='Result editor'><EmptyState title='No match' description='Unknown id.'/></PageContainer>; return <PageContainer title='Match Result Editor' subtitle='Mobile-friendly event flow'><div className='card space-y-3 p-4'><div className='grid grid-cols-2 gap-2'><Input defaultValue={String(match.homeScore ?? 0)} /><Input defaultValue={String(match.awayScore ?? 0)} /></div><Select defaultValue={match.status}><option value='upcoming'>Upcoming</option><option value='live'>Live</option><option value='finished'>Finished</option></Select><SectionHeader title='Quick add event' /><div className='grid gap-2 md:grid-cols-4'><Input placeholder="minute" /><Select><option>goal</option><option>yellow_card</option><option>red_card</option><option>substitution</option></Select><Select>{teams.map((t)=><option key={t.id}>{t.shortName}</option>)}</Select><Button>Add event</Button></div><div className='sticky bottom-16 border-t pt-3 md:bottom-2'><Button>Save result</Button></div></div></PageContainer>}

export const AdminSchedulePage = () => <PageContainer title='Admin Schedule'>{scheduleEntries.map((s)=><div key={s.id} className='card mb-2 p-3'>{s.date} · {s.note}</div>)}</PageContainer>;
export const AdminEventsPage = () => <PageContainer title='Admin Events'>{allEvents.map((e)=><div key={e.id} className='card mb-2 p-3'>{e.minute}' · {e.type} · {teams.find((t)=>t.id===e.teamId)?.shortName}</div>)}</PageContainer>;
export const AdminUsersPage = () => <PageContainer title='Admin Users'>{adminUsers.map((u)=><div key={u.id} className='card mb-2 flex items-center justify-between p-3'><div><p>{u.name}</p><p className='text-xs text-zinc-500'>{u.email}</p></div><span className='text-xs'>{u.role}</span></div>)}</PageContainer>;
